import Invoice, { INVOICE_STATUSES } from "../models/Invoice.js";
import { generateInvoiceNumber } from "../utils/generateInvoiceNumber.js";
import { notifyUser, logActivity } from "./notificationService.js";

/**
 * Creates an invoice directly linked to an order
 */
export const createInvoiceForOrder = async (order) => {
  const invoiceNumber = generateInvoiceNumber();

  const invoiceItems = order.items.map((item) => {
    let baseName = item.name || "Commercial Item";
    baseName = baseName.replace(/\s*\((CTN|Pieces|ctn|pieces|Units|units)\)\s*$/i, "").trim();

    const isPiece =
      item.isCarton === false ||
      item.unitType === "pieces" ||
      item.unitType === "units" ||
      item.unit === "pieces" ||
      item.unit === "units" ||
      /(Pieces|units)/i.test(item.name || item.description || "");

    const tag = isPiece ? "(Pieces)" : "(CTN)";
    const description = `${baseName} ${tag}`;

    return {
      description,
      quantity: item.quantity,
      unitPrice: item.price || item.unitPrice || item.wholesalePrice,
      total: item.subtotal,
      product: item.product,
    };
  });

  const invoice = await Invoice.create({
    invoiceNumber,
    order: order._id,
    customer: order.customer,
    items: invoiceItems,
    subtotal: order.subtotal,
    deliveryFee: order.deliveryFee || 0,
    total: order.totalAmount,
    status: order.paymentStatus === "Confirmed" ? "Paid" : "Pending",
    notes: order.notes || `Invoice for Order #${order.orderNumber}`,
  });

  return invoice;
};

/**
 * Creates a custom invoice generated by an admin
 */
export const createCustomInvoice = async ({
  customer,
  items,
  discount = 0,
  deliveryFee = 0,
  dueDate,
  notes = "",
  status = "Pending",
  createdBy,
}) => {
  if (!INVOICE_STATUSES.includes(status)) {
    throw new Error(
      `Invalid invoice status: '${status}'. Allowed statuses: ${INVOICE_STATUSES.join(", ")}`
    );
  }

  const invoiceNumber = generateInvoiceNumber();

  let subtotal = 0;
  const processedItems = items.map((item) => {
    const total = Number(item.quantity) * Number(item.unitPrice);
    subtotal += total;
    return {
      description: item.description,
      quantity: Number(item.quantity),
      unitPrice: Number(item.unitPrice),
      total,
      product: item.product || null,
    };
  });

  const finalTotal = Math.max(0, subtotal - Number(discount) + Number(deliveryFee));

  const invoice = await Invoice.create({
    invoiceNumber,
    customer,
    items: processedItems,
    subtotal,
    discount: Number(discount),
    deliveryFee: Number(deliveryFee),
    total: finalTotal,
    status,
    dueDate: dueDate ? new Date(dueDate) : null,
    notes,
    createdBy,
  });

  // Notify customer
  await notifyUser({
    recipientId: customer,
    type: "INVOICE_CREATED",
    title: "New Invoice Issued",
    message: `Invoice #${invoiceNumber} for ₦${finalTotal.toLocaleString()} has been issued to you.`,
    relatedInvoice: invoice._id,
  });

  // Log activity
  await logActivity({
    actorId: createdBy,
    action: "Admin created custom invoice",
    targetType: "Invoice",
    targetId: invoice._id,
    description: `Admin created custom invoice #${invoiceNumber} for customer`,
    metadata: { invoiceNumber, total: finalTotal, status },
  });

  return invoice;
};

/**
 * Updates invoice status
 */
export const updateInvoiceStatus = async (invoiceId, newStatus, actorId) => {
  if (!INVOICE_STATUSES.includes(newStatus)) {
    throw new Error(
      `Invalid status: '${newStatus}'. Allowed invoice statuses: ${INVOICE_STATUSES.join(", ")}`
    );
  }

  const invoice = await Invoice.findById(invoiceId);
  if (!invoice) {
    throw new Error("Invoice not found");
  }

  const previousStatus = invoice.status;
  invoice.status = newStatus;
  await invoice.save();

  // Log activity
  await logActivity({
    actorId,
    action: "Invoice status updated",
    targetType: "Invoice",
    targetId: invoice._id,
    description: `Invoice #${invoice.invoiceNumber} status changed from ${previousStatus} to ${newStatus}`,
    metadata: { previousStatus, newStatus },
  });

  return invoice;
};

export default {
  createInvoiceForOrder,
  createCustomInvoice,
  updateInvoiceStatus,
};
